#
# Autogenerated by Thrift Compiler (1.0.0-dev)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'tt_types'

module Demo
  module Hello
    class Client
      include ::Thrift::Client

      def helloString(para)
        send_helloString(para)
        return recv_helloString()
      end

      def send_helloString(para)
        send_message('helloString', HelloString_args, :para => para)
      end

      def recv_helloString()
        result = receive_message(HelloString_result)
        return result.success unless result.success.nil?
        raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'helloString failed: unknown result')
      end

    end

    class Processor
      include ::Thrift::Processor

      def process_helloString(seqid, iprot, oprot)
        args = read_args(iprot, HelloString_args)
        result = HelloString_result.new()
        result.success = @handler.helloString(args.para)
        write_result(result, oprot, 'helloString', seqid)
      end

    end

    # HELPER FUNCTIONS AND STRUCTURES

    class HelloString_args
      include ::Thrift::Struct, ::Thrift::Struct_Union
      PARA = 1

      FIELDS = {
        PARA => {:type => ::Thrift::Types::STRING, :name => 'para'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class HelloString_result
      include ::Thrift::Struct, ::Thrift::Struct_Union
      SUCCESS = 0

      FIELDS = {
        SUCCESS => {:type => ::Thrift::Types::STRING, :name => 'success'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

  end

end
